### ISSUE TITLE
No sound when pomodoro or break ends (+4 pomodoro issues)

### ISSUE THREAD

**Issue by brinkdinges** [toggl/track-windows-feedback#10]
**Describe the bug**
The old app had a sound that rings when the 25-minute pomodoro ends, or when the 5-minute break ends. That sounds is missing now.

**Steps to reproduce**
1. Enable pomodoros
1. Start the timer
2. Finish a pomodoro period
3. Hear no 'ding'

**Expected behavior**
The old sounds was perfect: very helpful and not annoying.

**Environment:**
 - Application version 8.04 (64 bit)
 - Windows 10 with latest updates

**Comment by brinkdinges** [comment]
I've been trying 8.04 and 8.05 for a week now on one pc and found using pomodoros to be close to unusable:

1. There is no sound when the work time or break time ends, so you easily miss it
2. The popup at the bottom right of the screen disappears after 8 seconds, so you miss that a period is over
3. The icon in the taskbar does not change color, only the icon on the right side of the taskbar does, so you think a timer is running while it is not. I notice myself checking the color of this icon ten times an hour

The old app had this process dialed in perfectly. I've been telling everyone about Toggl and how intuitive the software was. I hope we can reach that level again soon.

**Comment by sanyandreichuk** [comment]
@brinkdinges thanks for your feedback, we much appreciate it. Please update the app to `8.0.6` where some of the above issues were fixed. If you will notice any other issues feel free to reach out and we will try to fix them as soon as possible.

**Comment by brinkdinges** [comment]
Great, thanks. From what I've see so far, 1, 2 and 3 are fixed.

**Comment by brinkdinges** [comment]
It just saved a pomodoro under the project that was active. I used it all day yesterday and it didn't do that. Has the app updated itself in the meantime? It's running 8.0.7 now.

It's not just a display updating issue, the entry was saved under that project when the pomodoro break ended.

![image](https://user-images.githubusercontent.com/15387410/188307988-ac5deb5d-e4bf-4103-9056-367520f6fcde.png)

**Comment by brinkdinges** [comment]
Pomodoro breaks now also end up as 4:59 and not as 5 minutes.

**Comment by brinkdinges** [comment]
When you start a new pomodoro from the main window, the small pomodoro window does not get closed.

**Comment by brinkdinges** [comment]
I just woke up my laptop and Toggl proceeded to start a new pomodoro break. I have been out of the office for hours, where I use another computer with the old Toggl Track Windows app.

Another bug that I think I already reported via the in-app feedback. If you press Ctrl-O to continue a previous task, it restarts the pomodoro break and not the actual task.
