### ISSUE TITLE
Timer stuck in main UI

### ISSUE THREAD

**Issue by niklasholm** [toggl/track-windows-feedback#11]
**Describe the bug**
When I start an activity, the timer in the main UI stays stuck at 0:00:00, even though the activity is shown as ongoing in the Calendar-view and in the taskbar notification.

**Environment**
- Windows 10 21H2 build 19044.1889
 - 8.0.4 (64-bit)

**Additional context**
I installed this new version today because I got an prompt from the old version that it was being deprecated and I should upgrade. Very disappointed to see very blatant bugs right of the bat. The old version worked better.

**Comment by Merlin2001** [comment]
Restarting the app solves this issue for me, but I've been able to reproduce the stuck UI reliably by starting toggl on a remote machine (running Windows 10 21H2 build 19044.1889) and then disconnecting and reconnecting to that machine via Microsoft Remote Desktop.

**Comment by brinkdinges** [comment]
I have also seen this once and reported the issue via the internal feedback tool.

**Comment by niklasholm** [comment]
If it matters I'm also using Remote Desktop. I've never seen an issue caused by Remote Desktop like that before, is Toggl using some exotic rendering technique that's causing issues with RemoteFX?

**Comment by brinkdinges** [comment]
I'm not using Remote Desktop, but so far, it only happened once.

**Comment by focsi** [comment]
I have the same issue on Remote desktop.

**Comment by sanyandreichuk** [comment]
Thank you for your feedback. A new version `8.0.6` of the app is out, where this issue should be fixed.

**Comment by Merlin2001** [comment]
Can confirm that the issue is fixed in 8.0.6 for me 🚀 Thank you! 🙏

**Comment by niklasholm** [comment]
Fixed for me as well, closing. Thank you!
