### ISSUE TITLE
Switching from `Calendar` to `List` view and back again loses place

### ISSUE THREAD

**Issue by hamirmahal** [toggl/track-windows-feedback#13]
**Describe the bug**
Switching from `Calendar` to `List` view and back again loses the user's place.

**Steps to reproduce**
1. Go to `Calendar`.
2. Scroll down a bunch.
3. Go to `List` view.
4. Go back to `Calendar` view.

**Expected behavior**
The `Calendar` view should have saved the place the user was in, as opposed to scrolling to the top.

**Environment (please complete the following information):**
**I'm not able to copy and paste information in the `About` window, so I posted a screenshot below. Could the Toggl team make text in the `About` window copyable?**

![image](https://user-images.githubusercontent.com/43425812/189253114-12bda171-035e-4a69-b369-c9380fc1417f.png)

**Comment by kornelijepetak** [comment]
We're working on this as we speak and will be fixed in the following update.

Thanks for the reporting.

@toggl/windows reference: https://github.com/toggl/windows/issues/1171

**Comment by kornelijepetak** [comment]
This was fixed. Please make sure to update to the latest version.
