### ISSUE TITLE
Shortcuts (@ and #) don't work in manual mode

### ISSUE THREAD

**Issue by eltsele** [toggl/track-windows-feedback#17]
**Describe the bug**
If Toggl app is used in manual mode, the shortcuts for project and hashtags don't work.

**Steps to reproduce**
1. Swith the app to Manual Mode
2. Press the "Enter Time Manually" button
3. Press @ or # in the description pop-up and then first letters of project or tag
4. Nothing happens

**Expected behavior**
App should propose the project after pressing @ and the tag after pressing # basic on the letters you are typing.

**Environment (please complete the following information):**
 - Version 8.0.9

**Comment by kornelijepetak** [comment]
Moved to main repo for triage.
https://github.com/toggl/windows/issues/1311

**Comment by kornelijepetak** [comment]
This was solved. Please update to the latest version.
