### ISSUE TITLE
Tooltip information is empty on Windows 11

### ISSUE THREAD

**Issue by igor-oleks** [toggl/track-windows-feedback#2]
**Describe the bug**

It would be great to display information about the current task running (title, time)

**Steps to reproduce**

1. Open Toggl
2. Put its icon on the taskbar
3. Hover over it
4. See "ToolTip"

**Expected behaviour**

The title and time running of the current task is displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/100670062/182556433-243c1974-c9c6-4a91-8261-82106f1476ec.png)

**Environment (please complete the following information):**

 - Windows 11
 - Toggl 7.8.0

**Comment by kornelijepetak** [comment]
Hey, @ihor-oleks!
Thanks for the feedback.

We are aware of this bug and it is specific to Windows 11.
On Windows 10, the tooltip shown is a complex tooltip that looks like this:

![image](https://user-images.githubusercontent.com/7033216/183824445-7c8ea9ff-7f92-4faa-b7d1-2f9268935b53.png)

This seems [to be a bug in Windows 11](https://github.com/hardcodet/wpf-notifyicon/issues/65), and sadly, we're not too optimistic for Microsoft to fix this soon.
It seems that it does not allow us to properly show the whole content, but just a simple text label.

In the meantime, we'll try to find a workaround, to at least show the running time entry in a simple tooltip.

**Comment by kornelijepetak** [comment]
@igor-aleks 

With the latest Windows update `Build 22621.1343 (KB5022913)` the tooltip is displaying the correct content.
![image](https://user-images.githubusercontent.com/39395697/222380829-a4dfe75f-ecd7-4829-be30-d62799c975e9.png)

No Toggl Track update should be needed for this to apply.
