### ISSUE TITLE
Suggestion: Please add release date to your changelog

### ISSUE THREAD

**Issue by GitMurf** [toggl/track-windows-feedback#22]
The new Windows native app has been wonderful so far! Thank you for the great work. I just noticed we can now see a changelog in the About > Whats New menu. This is great. But could you add dates to each version entry so I can get an idea of when something was updated? I never know if there were recent updates to look at or if these maybe were from months ago. Thanks!

**Comment by kornelijepetak** [comment]
@GitMurf That is definitely what we should do! 😄

**Comment by ciltocruz** [comment]
Yes! Fixed!
![image](https://user-images.githubusercontent.com/19903919/225000863-3dfeb95c-d0cb-4798-b76f-cc26fd578f07.png)

**Comment by kornelijepetak** [comment]
@ciltocruz thanks for reminding me about this 😄 
The feature's been with us since `8.2.0` but I forgot to announce it here.

Keep the feedback coming 🙇  That's the only way forward!
