### ISSUE TITLE
Start/stop operations are slow

### ISSUE THREAD

**Issue by jeffmccormick** [toggl/track-windows-feedback#4]
**Describe the bug**
There is a considerable delay on UI visualization when starting and stopping entries. Other UI operations also appear to affected as well.

EDIT: After more observation, it appears this corresponds to when syncing occurs. It is likely syncing is being improperly run on the UI thread.

**Steps to reproduce**
Any/all button presses to start/stop time.

**Expected behavior**
Smooth UX transitions - no noticeable UI lag when performing operation.

EDIT: Offload syncing operations to the thread pool.

**Screenshots**
![TogglSlow](https://user-images.githubusercontent.com/13854173/185156028-d40974aa-5ddc-4eba-8633-a1cb7827f0e5.gif)

**Environment:**
 - Track Desktop v8.0.3 beta
 - Windows 10 21H2

**Comment by kornelijepetak** [comment]
Sorry for the late reply. 

This was a bug accidentally introduced in `8.0.3` and the issue has since been resolved in a later version, so please update your version.
