### ISSUE TITLE
Shortcut setting cannot recognize windows key

### ISSUE THREAD

**Issue by zhouxw-lang** [toggl/track-windows-feedback#5]
**Describe the bug**
Shortcut setting cannot recognize windows key. For example, if I press "Ctrl + Alt + Windows + O" to set the shortcut of Show/Hide Toggl Track, the result will be "Ctrl + Alt + O"

**Steps to reproduce**
1. Go to Preferences
2. Click on the input box to the right of "Show/Hide Toggl Track"
3. Press "Ctrl + Alt + Windows + O"
4. The content of the input box will become "Ctrl + Alt + O"

**Expected behavior**
The content of the input box should become "Ctrl + Alt + Windows + O"

**Screenshots**
<img src="https://user-images.githubusercontent.com/5899852/185361102-cdacdcf3-1bea-4d0a-ace7-15d0d6c8ac51.png" width="200">

**Environment (please complete the following information):**
 - Track Track v8.0.4

**Additional context**
Windows 11 Pro 21H2

**Comment by gkovacic** [comment]
Hey, @zhouxw-lang!
Thank you for your feedback.
The bug was fixed with the latest version of the app.
