### ISSUE TITLE
Showing/hiding app window is slow with a keyboard shortcut

### ISSUE THREAD

**Issue by svraka** [toggl/track-windows-feedback#6]
**Describe the bug**
Showing/hiding app window is slow with a keyboard shortcut.

**Steps to reproduce**
1. Set up a keyboard shortcut to show/hide Toggl Track.
2. Hide app with a keyboard shortcut.
3. Open app with a keyboard shortcut.

Steps 2-3 take around a second.

**Expected behavior**
Showing/hiding app window is immediate, just like by clicking the tray icon, or with the old version (7.5.454, 64 bit).

**Screenshots**
Not applicable, and I can't do a screen recording right now.

**Environment (please complete the following information):**
 - 8.0.4 (64 bit)

**Additional context**
N/A

**Comment by gkovacic** [comment]
Hey, @svraka!
Thank you for your feedback.
A new version of the app is out and hiding/showing the app should not be slow anymore.
But please feel free to report if you experience the lag again.

**Comment by svraka** [comment]
Yes, 8.0.5 solved the issue, thanks!
