### ISSUE TITLE
Memory leak related to the UI (300-850MB+ RAM usage)

### ISSUE THREAD

**Issue by W1Real** [toggl/track-windows-feedback#8]
**Describe the bug**
RAM isn't being flushed. `webFrame.clearCache()` every screen change might solve.

**Steps to reproduce**
Moving around the UI fast and repeatedly makes the RAM usage increase and never goes down to its base level of about 130MB.
- About 5 GB of free system RAM when I was running, so, probably any automatic garbage collection would not kick in.
- If you switch between the `List` and `Calendar` tab, vigorously repeatedly, by the human hand, does the most damage.
- Also, it got stuck eventually saying "Syncing" on top when I reached 850MB and just gave up on clicking anymore, after that, it became unresponsive, I still had enough free system RAM, and I had to force close it. Perhaps, unrelated to RAM usage?
- Just closing the UI into the system tray has no effect to recover the RAM usage.

**Expected behavior**
The older `(Version 7.5.454)` app doesn't seem to use more than about 100MB under any circumstances (from its base level of about 75MB when it starts up fresh), it tend to recover fast after the usage a bit increases. 

**Possible Solution:**
Running the open source software (avaliable on github) [`Mem Reduct`](https://github.com/henrypp/memreduct)  recovered the RAM, of both the old application (down to 30MB from 70MB from base level even), and also of every single Chrome/Electron Instance running on my system (Google Chrome & VScode). I believe your application uses Electron, if I'm not mistaken, so it explains the behaviour of the RAM usage. Perhaps if there is a way to force an electron instance to clean up, like how that `Mem Reduct` app does system-wide.

From what I found online using `webFrame.clearCache()` on every screen change on single page apps flushes it out. So, I believe there is hope to easily fix it, since it did somehow flush with `Mem Reduct`. Maybe even running `webFrame.clearCache()` every few seconds as well might be a good hack to mitigate RAM usage in a indiscriminate fashion throughout the whole application, but I don't know if it is common practice and its side-effects.

Here is a comprehensive article on it: [DEBUGGING ELECTRON MEMORY USAGE](https://seenaburns.com/debugging-electron-memory-usage/)

**Environment (please complete the following information):**
 - Application Version: `8.0.4 (64-bit)`
 - Windows 10 Enterprise, 10.0.19043 Build 19043
 - RAM 12GB (5GB free when running the test)
 - Processor	Intel Xeon E3-1220 v3 @ 3.10GHz (4x)
 - GPU: GTX 650 1GB (200Mb free when running the test)
 - Display: 4k, DPI 150%

**Comment by ToledoFor** [comment]
I confirm, but in my case, it's more interesting: the application uses about 8 GB of RAM!

![image](https://user-images.githubusercontent.com/114209657/193272597-c9370cdc-7beb-45a1-aa08-89b8bb24db1b.png)

**Comment by kornelijepetak** [comment]
Thanks guys for reporting this.

As for the app, it's not an electron app, it's a native Windows app, so unfortunatelly the suggested solution will not help.

However, we are aware that there's a memory leak and we're investigating it.
We'll try to solve it as soon as possible.

Given the amount of new features (and some improved UI elements), it is expected for the new app to take a bit more memory than the old one, but definitely not by a large margin. The expected memory footprint should definitely be under 200 MB and stable.

We'll let you know as soon as we find what's causing the issue.

Sorry for the inconvenience.

@W1Real If you can explain in a bit more detail what exactly you were doing to increase the mem footprint, it would be of tremendous help to us, especially if you can consistently reproduce it. Thanks a bunch.

**Comment by kornelijepetak** [comment]
Moved to main repo for triage.
https://github.com/toggl/windows/issues/1308

**Comment by kornelijepetak** [comment]
@W1Real As a follow up on this, have you noticed any memory issues in the most recent version of the app (`8.4.0`)?

**Comment by kornelijepetak** [comment]
Great, thanks for the followup.
