### ISSUE TITLE
No start menu entry

### ISSUE THREAD

**Issue by Tamriel** [toggl/track-windows-feedback#9]
On windows startup, Toggl starts. But in the start menu there is no entry!

**Comment by brinkdinges** [comment]
I see the same behavior in Windows 10 21H2, there is no entry and the search brings up nothing for either Track or Toggl.

**Comment by Merlin2001** [comment]
It's annoying a bit, but it's also a known issue listed in the readme.md on the front page:  
![image](https://user-images.githubusercontent.com/13134791/186122016-09b13ebb-197c-45bb-966e-64d1a4a2ba44.png)

You can create the shortcut yourself by pointing it to: 
`%LocalAppData%\TogglTrack\TogglTrack.exe`

(To create a new desktop shortcut: _Right click_ on desktop > _New_ > _Shortcut_ > Paste the path above > _Next_ > Type your desired name > _Finish_)

**Comment by gkovacic** [comment]
Thank you for your feedback. A new version of the app is out, with this issue fixed.
Please reinstall the app to have the Start menu shortcut available.
